// Builds a throwaway n8n workflow that applies one committed migration to the
// live `hov` database — so the SQL that runs is the committed file byte for
// byte, never a copy pasted into a tool call (see this folder's README).
//
//   node db/port/lib/make-apply.mjs db/014_project_activity.sql \
//     --verify db/port/activity-order/verify-014.sql \
//     --out db/port/activity-order/apply-014.workflow.js
//
// The first of these (db/port/playlists/make-apply.mjs, db/013) was written
// for one file; this is it made general. What it wraps around the file:
//
//   set local lock_timeout = '5s'  — an ALTER or a foreign key on hov.project
//       takes a lock the pipeline's own writes queue behind. Five seconds and
//       out, rather than a pipeline stalled behind a waiting DDL.
//   reset search_path              — every migration starts with a session
//       `set search_path to hov, public` (psql runs it outside a transaction);
//       through n8n it would stay on a pooled connection. The whole string is
//       one implicit transaction (simple query protocol), so success resets
//       it and failure rolls back every SET with everything else.
//
// What it refuses: `$` followed by a DIGIT (n8n's Postgres node reads it as a
// positional parameter under transaction batching — CLAUDE.md) and `{{` (an n8n
// expression). Dollar-quoted bodies like `$fn$ … $fn$` are fine and allowed:
// neither pg-promise's formatter nor n8n reads a `$` followed by a letter.
import { readFileSync, writeFileSync } from "node:fs";
import { basename } from "node:path";

const args = process.argv.slice(2);
const flag = (name) => {
  const i = args.indexOf(name);
  return i === -1 ? null : args[i + 1];
};
const file = args.find((a) => a.endsWith(".sql") && a !== flag("--verify"));
const verifyFile = flag("--verify");
const out = flag("--out");
if (!file || !verifyFile || !out) {
  console.error("usage: make-apply.mjs <db/NNN_name.sql> --verify <verify.sql> --out <apply.workflow.js>");
  process.exit(2);
}
const sql = readFileSync(file, "utf8");
const verify = readFileSync(verifyFile, "utf8").trim().replace(/;\s*$/, "");
for (const [what, text] of [["the migration", sql], ["the verify query", verify]]) {
  if (/\$\d/.test(text)) throw new Error(`${what} contains $<digit> — n8n would read it as a parameter`);
  if (text.includes("{{")) throw new Error(`${what} contains {{ — n8n would read it as an expression`);
}
const num = basename(file).slice(0, 3);
const applySql = `set local lock_timeout = '5s';\n${sql}\nreset search_path;\n`;

const code = `import { workflow, node, trigger } from '@n8n/workflow-sdk';

// GENERATED by db/port/lib/make-apply.mjs from ${file} — edit that, not this.

const startTrigger = trigger({ type: 'n8n-nodes-base.manualTrigger', version: 1, config: { name: 'Start', position: [240, 300] }, output: [{}] });

const apply = node({
  type: 'n8n-nodes-base.postgres', version: 2.7,
  config: { name: 'Apply ${num}', parameters: { resource: 'database', operation: 'executeQuery', query: ${JSON.stringify(applySql)}, options: {} }, credentials: { postgres: { id: 'eRjiNDQFuDSTJpGK', name: 'HOV Postgres' } }, position: [540, 300] },
  output: [{}]
});

const verify = node({
  type: 'n8n-nodes-base.postgres', version: 2.7,
  config: { name: 'Verify ${num}', executeOnce: true, parameters: { resource: 'database', operation: 'executeQuery', query: ${JSON.stringify(verify)}, options: {} }, credentials: { postgres: { id: 'eRjiNDQFuDSTJpGK', name: 'HOV Postgres' } }, position: [840, 300] },
  output: [{}]
});

export default workflow('apply-${num}', 'zz apply ${basename(file, ".sql")}')
  .add(startTrigger)
  .to(apply)
  .to(verify);
`;
writeFileSync(out, code);
console.log(`wrote ${out} (${code.length} bytes; ${basename(file)} is ${sql.length} bytes of it, embedded verbatim)`);
