// Builds apply-013.workflow.js from db/013_playlists.sql, so the SQL that runs
// on the live database is the committed file byte for byte — never a copy
// pasted into a tool call (the rule in db/port/lib/README.md).
//
//   node db/port/playlists/make-apply.mjs
//
// What it wraps around the file, and why:
//
//   set local lock_timeout = '5s'   — creating a table that REFERENCES
//       hov.project takes a brief lock on project. If some long transaction
//       already holds one, a plain CREATE would queue behind it and every
//       pipeline write to project would queue behind the CREATE. Five seconds
//       and out is the polite version: the apply fails, nothing waits.
//   reset search_path               — the file begins with a session-level
//       `set search_path to hov, public`, like every migration here, because
//       psql runs it outside a transaction. Sent through n8n it would stay on
//       whichever pooled connection ran it. The whole string is ONE implicit
//       transaction (simple query protocol, no BEGIN), so on success the reset
//       puts the connection back, and on failure the rollback undoes every SET
//       along with everything else.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const sql = readFileSync(join(here, "..", "..", "013_playlists.sql"), "utf8");
if (sql.includes("$") || sql.includes("{{")) {
  throw new Error("013 contains $ or {{ — n8n would read it as a parameter or an expression");
}
const applySql = `set local lock_timeout = '5s';\n${sql}\nreset search_path;\n`;

const verifySql = `select
  (select count(*)::int from information_schema.tables
    where table_schema = 'hov' and table_name in ('playlist', 'playlist_project')) as new_tables,
  (select count(*)::int from pg_indexes
    where schemaname = 'hov' and indexname in ('playlist_name_idx', 'playlist_project_project_idx')) as new_indexes,
  (select count(*)::int from pg_trigger where tgname = 'playlist_touch') as trigger_present,
  (select count(*)::int from pg_constraint
    where conrelid = 'hov.playlist_project'::regclass and contype = 'f' and confdeltype = 'c') as cascading_fks,
  (select count(*)::int from pg_constraint
    where conrelid = 'hov.playlist'::regclass and contype = 'c') as name_checks,
  (select count(*)::int from hov.playlist) as playlist_rows,
  (select count(*)::int from hov.project) as projects`;

const code = `import { workflow, node, trigger } from '@n8n/workflow-sdk';

// GENERATED by db/port/playlists/make-apply.mjs from db/013_playlists.sql — edit those, not this.

const startTrigger = trigger({ type: 'n8n-nodes-base.manualTrigger', version: 1, config: { name: 'Start', position: [240, 300] }, output: [{}] });

const apply = node({
  type: 'n8n-nodes-base.postgres', version: 2.7,
  config: { name: 'Apply 013', parameters: { resource: 'database', operation: 'executeQuery', query: ${JSON.stringify(applySql)}, options: {} }, credentials: { postgres: { id: 'eRjiNDQFuDSTJpGK', name: 'HOV Postgres' } }, position: [540, 300] },
  output: [{}]
});

const verify = node({
  type: 'n8n-nodes-base.postgres', version: 2.7,
  config: { name: 'Verify 013', executeOnce: true, parameters: { resource: 'database', operation: 'executeQuery', query: ${JSON.stringify(verifySql)}, options: {} }, credentials: { postgres: { id: 'eRjiNDQFuDSTJpGK', name: 'HOV Postgres' } }, position: [840, 300] },
  output: [{ new_tables: 2, new_indexes: 2, trigger_present: 1, cascading_fks: 2, name_checks: 1, playlist_rows: 0, projects: 1 }]
});

export default workflow('apply-013-playlists', 'zz apply db/013 playlists')
  .add(startTrigger)
  .to(apply)
  .to(verify);
`;
writeFileSync(join(here, "apply-013.workflow.js"), code);
console.log(`wrote apply-013.workflow.js (${code.length} bytes; the migration is ${sql.length} bytes of it)`);
