-- House of Videos — the database that replaces Airtable.
--
-- Runs in the postgres:16 container already on the box (compose project
-- `n8n`), in its own database `hov` with its own role. n8n's own database is
-- untouched.
--
-- Two rules shaped everything here:
--
-- 1. **Record ids keep Airtable's shape.** `rec` + 14 chars, generated by
--    gen_rec_id(). The site puts scene ids in webhook payloads, n8n passes
--    them between workflows, and old rows carry the ids Airtable minted. A
--    UUID would have forced a rewrite of every stored reference and broken
--    every project in flight on cutover day. So the import copies Airtable's
--    ids verbatim and new rows get ids nothing downstream can tell apart.
--
-- 2. **Columns are named for what they HOLD, not what Airtable called them.**
--    Several Airtable fields were reused for something other than their name
--    years ago and the name stuck. Each column carries its Airtable original
--    in a COMMENT, so the mapping is queryable from the database itself:
--        select column_name, col_description(...) from information_schema...
--    The three that bite are marked LEGACY below. Read them before porting
--    any n8n node.

create schema if not exists hov;
set search_path to hov, public;

-- ---------------------------------------------------------------------------
-- Airtable-shaped ids
-- ---------------------------------------------------------------------------

create or replace function gen_rec_id() returns text
  language sql volatile as $$
  select 'rec' || string_agg(
    substr('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ',
           1 + floor(random() * 62)::int, 1), '')
  from generate_series(1, 14);
$$;

comment on function gen_rec_id() is
  'Mints an id indistinguishable from an Airtable record id (rec + 14 chars). '
  'Deliberate: the site and n8n pass these ids around as opaque strings and '
  'must not be able to tell an imported row from a new one.';

-- Every table gets updated_at maintained here rather than by the caller —
-- Airtable had no such field and n8n would have had to remember to write it
-- on all ~40 of its write nodes.
create or replace function touch_updated_at() returns trigger
  language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- project  (Airtable: "Proiecte")
-- ---------------------------------------------------------------------------

create table project (
  id                      text primary key default gen_rec_id(),
  name                    text not null default 'Untitled project',
  tone                    text,
  aspect                  text not null default '16:9'
                            check (aspect in ('16:9', '9:16')),
  no_captions             boolean not null default false,
  pace                    text,

  -- CHECK > 0, and that is the whole point of this column existing here.
  -- `Update Status to Finished` used to map Lenght: 0 explicitly, wiping the
  -- length of every project that reached the end of the happy path. Silent
  -- until a restart, then lethal: scripting derives chapter count from
  -- ceil(length/120), so a restarted film was written against zero. In
  -- Airtable nothing could refuse that write. Here it cannot be committed.
  length_seconds          integer check (length_seconds is null or length_seconds > 0),

  status                  text not null default 'Planificat',
  final_video_url         text,
  estimated_finish        text,
  editing_options         jsonb not null default '{}'::jsonb,
  tags                    text[] not null default '{}',
  language                text not null default '',
  style                   text,
  story_bible             text,
  scene_note              text,
  full_narrator_script    text,
  edited_narrator_script  text,
  script_chapters         jsonb,
  script_status           boolean not null default false,
  voice_id                text not null default '',
  research_thin           boolean not null default false,

  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

comment on column project.name is                   'Airtable: "Nume Proiect"';
comment on column project.tone is                   'Airtable: "Tonalitate" — joins genre_profile.tone';
comment on column project.aspect is                 'Airtable: "Format" (singleSelect)';
comment on column project.no_captions is            'Airtable: "Fără Subtitrări"';
comment on column project.length_seconds is         'Airtable: "Lenght" (the typo is original)';
comment on column project.status is                 'Airtable: "Status General" — Romanian, written by n8n, parsed by STATUS_MAP in platform/lib/data.ts. Values are NOT translated on migration.';
comment on column project.final_video_url is        'Airtable: "Link Video Final"';
comment on column project.estimated_finish is       'Airtable: "Data Finalizare Estimată" (free text, never parsed)';
comment on column project.editing_options is        'Airtable: "Editing Options" — was a JSON string in a multilineText, now real jsonb. Carries hookTitle, chapterCards, endScreen, sfx, music, category, multiVoiceMode, cast, castAssign, chapterVoices, refImage.';
comment on column project.scene_note is             'Airtable: "Scene" (singleLineText) — not the scene table, an unrelated free-text field';
comment on column project.script_chapters is        'Airtable: "Script Chapters JSON"';
comment on column project.voice_id is               'Airtable: "Voice ID" — ai33/ElevenLabs id chosen at creation';
comment on column project.research_thin is          'Airtable: "Research Thin" — research returned <6 sourced claims; treat factual content as unverified';

-- "Project ID" in Airtable was a formula field equal to RECORD_ID(). It has
-- no counterpart here on purpose: it was always just the id. Anything reading
-- Project_ID reads project.id.

create index project_status_idx     on project (status);
create index project_created_at_idx on project (created_at desc);

create trigger project_touch before update on project
  for each row execute function touch_updated_at();

-- ---------------------------------------------------------------------------
-- chapter  (Airtable: "Capitole")
-- ---------------------------------------------------------------------------

create table chapter (
  id                text primary key default gen_rec_id(),
  project_id        text not null references project(id) on delete cascade,
  title             text,
  main_ideas        text,
  chapter_script    text,
  ordinal           integer check (ordinal is null or ordinal > 0),
  approval_status   text,
  notes             text,
  owner             text,
  duration_minutes  numeric check (duration_minutes is null or duration_minutes > 0),
  scene_note        text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

comment on column chapter.title is            'Airtable: "Titlu Capitol"';
comment on column chapter.main_ideas is       'Airtable: "Idei Principale"';
comment on column chapter.chapter_script is   'Airtable: "Script Capitol"';
comment on column chapter.ordinal is          'Airtable: "Ordine"';
comment on column chapter.approval_status is  'Airtable: "Status Aprobare Capitol"';
comment on column chapter.notes is            'Airtable: "Observații Capitol"';
comment on column chapter.owner is            'Airtable: "Responsabil Capitol"';
comment on column chapter.scene_note is       'Airtable: "Scene" (singleLineText on Capitole)';

create index chapter_project_idx on chapter (project_id, ordinal);

create trigger chapter_touch before update on chapter
  for each row execute function touch_updated_at();

-- ---------------------------------------------------------------------------
-- scene  (Airtable: "Scene")
--
-- The hot table. Both the site and n8n hit it constantly: the site re-reads
-- it on every click (force-dynamic), and Evaluate Image/Voice/Video Approval
-- poll it every 15 seconds from inside a live execution.
-- ---------------------------------------------------------------------------

create table scene (
  id                text primary key default gen_rec_id(),

  -- Airtable linked to the chapter and duplicated the project into a text
  -- field ("Project_ID") that getScenes() filtered on. Both are real foreign
  -- keys here. project_id stays denormalised because every hot query filters
  -- on it, but it is now a key the database enforces rather than a string
  -- that could drift.
  project_id        text not null references project(id) on delete cascade,
  chapter_id        text references chapter(id) on delete set null,

  narration         text,

  -- LEGACY (1/3). Airtable's "Imagine First Frame" is url-typed and named for
  -- a frame, but what it actually holds — and what the site reads as the
  -- image prompt — is prompt TEXT. See F.sceneImagePrompt in
  -- platform/lib/data.ts. Do not "fix" this by pointing it at an image.
  image_prompt      text,

  -- LEGACY (2/3). Airtable's "Video Scenă URL" holds the motion PROMPT, not a
  -- link, from an old reuse of the field. Never read it as a URL.
  motion_prompt     text,

  visual_prompt     text,
  last_frame_url    text,
  voiceover_url     text,

  -- LEGACY (3/3). The clip the site plays is "Scene Final URL" — video +
  -- that scene's own audio, muxed per scene before final concatenation —
  -- falling back to the "Video Scenă" attachment. Both are represented:
  -- this column, and an attachment row with field='video'.
  scene_final_url   text,

  image_media_id    text,

  -- Same reasoning as project.length_seconds: fifteen n8n nodes were mapping
  -- this with no value, which in Airtable writes a literal 0 rather than
  -- skipping the field. Combined with the batch's sort that sent processed
  -- scenes to order 0, one unprocessed scene held the only non-zero order,
  -- sorted last and fell off the end of the cap forever.
  scene_order       integer not null check (scene_order > 0),
  duration_seconds  numeric check (duration_seconds is null or duration_seconds > 0),

  production_status text not null default 'Generare Script',

  scene_approved    boolean not null default false,
  image_approved    boolean not null default false,
  voice_approved    boolean not null default false,
  video_approved    boolean not null default false,

  -- The regen flags are set by the site and cleared by n8n from INSIDE the
  -- execution, so any death in between strands them — and the UI renders the
  -- in-flight state INSTEAD of the button row, which makes a stranded flag a
  -- dead end rather than a nuisance. Airtable offered nothing to detect that,
  -- so each state needed a hand-built escape hatch and two still have none.
  -- The *_at columns make staleness a query:
  --     where regen_image and regen_image_at < now() - interval '10 minutes'
  -- One rule covers every flag, including the ones added later.
  regen_image       boolean not null default false,
  regen_image_at    timestamptz,
  regen_video       boolean not null default false,
  regen_video_at    timestamptz,
  regen_voice       boolean not null default false,
  regen_voice_at    timestamptz,

  note              text,
  tags              text[] not null default '{}',
  evidence_ref      text,
  needs_fact_check  boolean not null default false,
  media_versions    jsonb not null default '[]'::jsonb,

  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

comment on column scene.narration is         'Airtable: "Script Scenă" (the primary field)';
comment on column scene.image_prompt is      'Airtable: "Imagine First Frame" — LEGACY, holds prompt text despite the name';
comment on column scene.motion_prompt is     'Airtable: "Video Scenă URL" — LEGACY, holds the motion prompt, never a URL';
comment on column scene.visual_prompt is     'Airtable: "Prompt Vizual"';
comment on column scene.last_frame_url is    'Airtable: "Imagine Last Frame"';
comment on column scene.voiceover_url is     'Airtable: "Voiceover URL"';
comment on column scene.scene_final_url is   'Airtable: "Scene Final URL" — the muxed per-scene clip the site plays';
comment on column scene.image_media_id is    'Airtable: "Image Media ID" — Flow mediaGenerationId, used as startImage for video and as style reference for the next scene';
comment on column scene.scene_order is       'Airtable: "Ordine Scenă" — encodes chapter*100 + scene, so values like 102 and 311 are normal. NOT a 1..N sequence.';
comment on column scene.production_status is 'Airtable: "Status Producție Scenă" — result stamps only, never progress. The site DERIVES display status from checkboxes + asset existence and reads this only for errors and Regenerare Text.';
comment on column scene.media_versions is    'Airtable: "Versiuni Media" — saved draft descriptors; image entries name an attachment row, video entries carry a Drive URL';

create index scene_project_order_idx on scene (project_id, scene_order);
create index scene_chapter_idx       on scene (chapter_id);
-- The approval poll: n8n asks "are this batch's scenes signed off" every 15s.
create index scene_approval_idx      on scene (project_id)
  where not (image_approved and voice_approved and video_approved);
-- Stranded-flag sweep.
create index scene_regen_idx         on scene (project_id)
  where regen_image or regen_video or regen_voice;

create trigger scene_touch before update on scene
  for each row execute function touch_updated_at();

-- ---------------------------------------------------------------------------
-- attachment — what replaces Airtable's file hosting
--
-- This is the part Airtable was silently doing for free, and the reason the
-- pipeline works at all: fal and Flow hand back signed CDN links that expire
-- in hours, and re-uploading them into an Airtable attachment field made
-- Airtable re-host the bytes permanently. Postgres stores no files, so the
-- bytes now live on the box under /opt/n8n/media and Caddy serves them at
-- /media/*. This table is the index.
--
-- One table for all three of Airtable's attachment fields, discriminated by
-- `field`, because they differ only in cardinality: image/video are one per
-- scene, image_version is many.
-- ---------------------------------------------------------------------------

create table attachment (
  id            text primary key default gen_rec_id(),
  scene_id      text not null references scene(id) on delete cascade,
  field         text not null check (field in ('image', 'video', 'image_version')),

  -- Path under the media root, e.g. 'recXXXX/image/9f8a....png'. The public
  -- URL is MEDIA_BASE_URL || '/' || path. Storing the path and not the URL
  -- keeps the rows valid if the host or scheme ever changes.
  path          text not null unique,
  filename      text,
  content_type  text,
  size_bytes    bigint check (size_bytes is null or size_bytes >= 0),
  width         integer,
  height        integer,

  -- Where the bytes came from, kept for provenance and for re-download if an
  -- import is ever re-run against a still-live source.
  source_url    text,

  created_at    timestamptz not null default now()
);

comment on table attachment is
  'Index of files under /opt/n8n/media. Replaces Airtable attachment fields: '
  'field=image is "Imagine Scenă", field=video is "Video Scenă", '
  'field=image_version is "Versiuni Imagine".';

create index attachment_scene_idx on attachment (scene_id, field);
-- One current image and one current video per scene; drafts are unbounded.
create unique index attachment_one_per_field_idx on attachment (scene_id, field)
  where field in ('image', 'video');

-- ---------------------------------------------------------------------------
-- script  (Airtable: "Scripturi")
-- ---------------------------------------------------------------------------

create table script (
  id              text primary key default gen_rec_id(),
  project_id      text references project(id) on delete cascade,
  title           text,
  content         text,
  chapters        text,
  status          text,
  language        text,
  notes           text,
  summary         text,
  headline        text,
  regenerate      boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

comment on column script.title is      'Airtable: "Script Title"';
comment on column script.content is    'Airtable: "Script Content"';
comment on column script.chapters is   'Airtable: "script chapters"';
comment on column script.notes is      'Airtable: "Observații Script"';
comment on column script.summary is    'Airtable: "Summary (Observații Script)" — was an aiText field. Airtable generated this on write; nothing regenerates it here, so it is frozen at its imported value until something is wired to fill it.';
comment on column script.headline is   'Airtable: "Headline (Observații Script)" — was an aiText field, same caveat as summary';
comment on column script.regenerate is 'Airtable: "Regenerează Video"';

create index script_project_idx on script (project_id);

create trigger script_touch before update on script
  for each row execute function touch_updated_at();

-- ---------------------------------------------------------------------------
-- evidence  (Airtable: "Evidence")
-- ---------------------------------------------------------------------------

create table evidence (
  id           text primary key default gen_rec_id(),
  project_id   text not null references project(id) on delete cascade,
  ref          text not null,
  claim        text,
  source_name  text,
  source_url   text,
  source_date  text,
  created_at   timestamptz not null default now()
);

comment on column evidence.ref is 'Airtable: "Ref" — the E1/E2/E3 label scenes cite in scene.evidence_ref';
comment on column evidence.source_date is 'Airtable: "Source Date" — free text, never parsed as a date';

-- Scenes cite these by ref (E1, E3…) in scene.evidence_ref. A ref must be
-- unique within its project or a citation is ambiguous — Airtable could not
-- express that.
create unique index evidence_project_ref_idx on evidence (project_id, ref);

-- ---------------------------------------------------------------------------
-- genre_profile  (Airtable: "Genre Profiles")
--
-- One of the three tables humans edit by hand. Claude Scripting fetches the
-- row matching the project's tone at the start of every run and injects each
-- column into its prompts, so editing a cell changes the next film with no
-- workflow change. That property has to survive the migration — see the
-- admin screens in the site.
-- ---------------------------------------------------------------------------

create table genre_profile (
  id                  text primary key default gen_rec_id(),
  tone                text not null,
  format              text,
  research            boolean not null default false,
  research_brief      text,
  fact_sheet_framing  text,
  invention           text,
  structure           text,
  voice               text,
  wpm                 integer check (wpm is null or wpm > 0),
  hook_rule           text,
  visual              text,
  montage_intensity   integer not null default 1
                        check (montage_intensity between 0 and 2),
  active              boolean not null default true,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

comment on column genre_profile.tone is
  'Must match the site form''s Tone option (case-insensitive). Scripting looks '
  'the row up by this and falls back to its built-in profiles if absent.';
comment on column genre_profile.montage_intensity is
  'Airtable: "Montage Intensity" — 0 calm, 1 default, 2 aggressive. Airtable '
  'allowed any number; the range is enforced here.';

-- The lookup is case-insensitive, so the uniqueness has to be too — two rows
-- differing only in case would make which profile wins depend on row order.
create unique index genre_profile_tone_idx on genre_profile (lower(tone));

create trigger genre_profile_touch before update on genre_profile
  for each row execute function touch_updated_at();

-- ---------------------------------------------------------------------------
-- script_library  (Airtable: "Script Library")
-- ---------------------------------------------------------------------------

create table script_library (
  id                text primary key default gen_rec_id(),
  title             text not null,
  source_url        text,
  category          text,
  tone              text,
  raw_transcript    text,
  style_card        text,
  pacing_wpm        integer check (pacing_wpm is null or pacing_wpm > 0),
  hook_wpm          integer check (hook_wpm is null or hook_wpm > 0),
  duration_seconds  integer check (duration_seconds is null or duration_seconds > 0),
  transcript_source text,
  active            boolean not null default false,
  notes             text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index script_library_active_idx on script_library (active) where active;

create trigger script_library_touch before update on script_library
  for each row execute function touch_updated_at();

-- ---------------------------------------------------------------------------
-- script_example  (Airtable: "Librărie Scripturi")
-- ---------------------------------------------------------------------------

create table script_example (
  id           text primary key default gen_rec_id(),
  name         text not null,
  content      text,
  style        text[] not null default '{}',
  tags         text[] not null default '{}',
  usage_url    text,
  notes        text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on column script_example.name is    'Airtable: "Nume Exemplu"';
comment on column script_example.content is 'Airtable: "Conținut Script"';
comment on column script_example.style is   'Airtable: "Stil" (multipleSelects)';
comment on column script_example.tags is    'Airtable: "Tag-uri Script" (multipleSelects)';

create trigger script_example_touch before update on script_example
  for each row execute function touch_updated_at();
