// Builds the n8n "API Credits" workflow (SDK code) from the committed node
// bodies in paste/, so what runs in n8n is those files byte for byte.
//
//   node db/port/api-credits/build.mjs
//       → writes api-credits.workflow.js beside this file, with the useapi
//         token as the placeholder __USEAPI_TOKEN__ (that file is committed)
//   node db/port/api-credits/build.mjs --token-file <file> --out <path>
//       → the same code with the real token, for create_workflow_from_code.
//         Write it OUTSIDE the repo (the session scratchpad).
//
// Why the token is pasted and not a credential: useapi has no n8n credential
// in this instance — the same token is hard-coded in 14 Media Generation nodes
// and one Claude Scripting node (CLAUDE.md: "rotate the useapi token"). When it
// is rotated, this workflow's four useapi nodes rotate with them; better
// still, move all of them to one Header Auth credential.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const flag = (name) => {
  const i = args.indexOf(name);
  return i === -1 ? null : args[i + 1];
};
const body = (name) => readFileSync(join(here, "paste", `${name}.js`), "utf8");
for (const n of ["Flow Emails", "Normalize", "Result"]) {
  const b = body(n);
  if (b.includes("{{")) throw new Error(`${n}: contains {{ — n8n would read it as an expression`);
}

const OAI = "{ openAiApi: { id: 'oPGuXelJ6pnDePIs', name: 'OpenAI account' } }";
const EL = "{ elevenLabsApi: { id: 'VbtLxHjVO7QySxfz', name: 'ElevenLabs account' } }";
const DRIVE = "{ googleDriveOAuth2Api: { id: 'dv4yT9vojdPQoO17', name: 'Google Drive account' } }";
const KEY = "{ httpHeaderAuth: { id: '8kpY42LmZaBYBzfY', name: 'HOV Media Ingest' } }";
const PG = "{ postgres: { id: 'eRjiNDQFuDSTJpGK', name: 'HOV Postgres' } }";
const UA = "sendHeaders: true, headerParameters: { parameters: [{ name: 'Authorization', value: 'Bearer __USEAPI_TOKEN__' }] }";
// Every probe answers with its status instead of throwing: a refusal is a
// reading, and one provider being down must not blank the whole page.
const PROBE = "options: { timeout: 20000, response: { response: { fullResponse: true, neverError: true } } }";

const http = (v, name, x, y, params, cred) =>
  `const ${v} = node({ type: 'n8n-nodes-base.httpRequest', version: 4.4, config: { name: '${name}', onError: 'continueRegularOutput', parameters: { ${params}, ${PROBE} }${cred ? `, credentials: ${cred}` : ""}, position: [${x}, ${y}] }, output: [{}] });`;
const code = (v, name, x, y, jsCode, extra = "") =>
  `const ${v} = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: '${name}'${extra}, parameters: { jsCode: ${JSON.stringify(jsCode)} }, position: [${x}, ${y}] }, output: [{}] });`;

const lines = [
  "import { workflow, node, trigger } from '@n8n/workflow-sdk';",
  "",
  "// GENERATED by db/port/api-credits/build.mjs from paste/ — edit those, not this.",
  "",
  "const hourly = trigger({ type: 'n8n-nodes-base.scheduleTrigger', version: 1.2, config: { name: 'Every Hour', parameters: { rule: { interval: [{ field: 'hours', hoursInterval: 1 }] } }, position: [0, 200] }, output: [{}] });",
  `const hook = trigger({ type: 'n8n-nodes-base.webhook', version: 2, config: { name: 'Credits Webhook', parameters: { httpMethod: 'POST', path: 'api-credits', authentication: 'headerAuth', responseMode: 'lastNode', options: {} }, credentials: ${KEY}, position: [0, 400] }, output: [{}] });`,
  "",
  http("oaiPing", "OpenAI Ping", 240, 300, "method: 'POST', url: 'https://api.openai.com/v1/chat/completions', authentication: 'predefinedCredentialType', nodeCredentialType: 'openAiApi', sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: '{\"model\":\"gpt-4o-mini\",\"messages\":[{\"role\":\"user\",\"content\":\"ok\"}],\"max_tokens\":1}'", OAI),
  http("oaiCosts", "OpenAI Costs", 480, 300, "method: 'GET', url: '={{ \"https://api.openai.com/v1/organization/costs?start_time=\" + Math.floor(Date.now() / 1000 - 30 * 86400) + \"&bucket_width=1d&limit=31&group_by=line_item\" }}', authentication: 'predefinedCredentialType', nodeCredentialType: 'openAiApi'", OAI),
  http("elSub", "ElevenLabs Subscription", 720, 300, "method: 'GET', url: 'https://api.elevenlabs.io/v1/user/subscription', authentication: 'predefinedCredentialType', nodeCredentialType: 'elevenLabsApi'", EL),
  http("elUsage", "ElevenLabs Usage", 960, 300, "method: 'GET', url: '={{ \"https://api.elevenlabs.io/v1/usage/character-stats?start_unix=\" + (Date.now() - 30 * 86400000) + \"&end_unix=\" + Date.now() + \"&aggregation_interval=day\" }}', authentication: 'predefinedCredentialType', nodeCredentialType: 'elevenLabsApi'", EL),
  http("drive", "Drive About", 1200, 300, "method: 'GET', url: 'https://www.googleapis.com/drive/v3/about?fields=storageQuota,user', authentication: 'predefinedCredentialType', nodeCredentialType: 'googleDriveOAuth2Api'", DRIVE),
  http("uaMe", "useapi Account", 1440, 300, `method: 'GET', url: 'https://api.useapi.net/v1/account', ${UA}`),
  http("uaList", "Flow Accounts", 1680, 300, `method: 'GET', url: 'https://api.useapi.net/v1/google-flow/accounts', ${UA}`),
  code("emails", "Flow Emails", 1920, 300, body("Flow Emails"), ", executeOnce: true"),
  http("uaOne", "Flow Account", 2160, 300, `method: 'GET', url: '={{ $json.email ? "https://api.useapi.net/v1/google-flow/accounts/" + encodeURIComponent($json.email) : "https://api.useapi.net/v1/account" }}', ${UA}`),
  code("normalize", "Normalize", 2400, 300, body("Normalize"), ", executeOnce: true"),
  `const save = node({ type: 'n8n-nodes-base.postgres', version: 2.7, config: { name: 'Save Snapshot', onError: 'continueRegularOutput', parameters: { resource: 'database', operation: 'executeQuery', query: '={{ $json.sql }}', options: {} }, credentials: ${PG}, position: [2640, 300] }, output: [{}] });`,
  code("result", "Result", 2880, 300, body("Result"), ", executeOnce: true"),
  "",
  "export default workflow('api-credits', 'API Credits')",
  "  .add(hourly)",
  "  .to(oaiPing)",
  "  .to(oaiCosts)",
  "  .to(elSub)",
  "  .to(elUsage)",
  "  .to(drive)",
  "  .to(uaMe)",
  "  .to(uaList)",
  "  .to(emails)",
  "  .to(uaOne)",
  "  .to(normalize)",
  "  .to(save)",
  "  .to(result)",
  "  .add(hook)",
  "  .to(oaiPing);",
  "",
];
let out = lines.join("\n");
const tokenFile = flag("--token-file");
const target = flag("--out") ?? join(here, "api-credits.workflow.js");
if (tokenFile) {
  const token = readFileSync(tokenFile, "utf8").trim();
  if (!/^user:\d+-[A-Za-z0-9]+$/.test(token)) throw new Error("the token file does not hold a useapi token");
  if (target.startsWith(join(here, "..", "..", ".."))) throw new Error("refusing to write the real token inside the repo");
  out = out.replaceAll("__USEAPI_TOKEN__", token);
}
writeFileSync(target, out);
console.log(`wrote ${target} (${out.length} chars)`);
